"""Write the gate table into docs/compliance_matrix.md from bench/results/gates.json.

## Why this is a script and not a paragraph of discipline

The compliance matrix already claimed its gate table was "Generated by `bench/gates.py`". It
was not. `bench/gates.py` writes `bench/results/gates.md`; nothing ever touched the matrix, so
the table was transcribed by hand and drifted -- its A-RUNTIME row still read "worst 43.4 s"
long after that row had been deliberately changed to stop embedding wall-clock in a result.

A claim that a document is generated is worth less than nothing when it is false: it tells a
reader they need not check the one thing that is wrong. So the table is now actually generated,
between markers, and `tests/test_traceability.py` fails if the committed file is out of sync.

    python scripts/sync_compliance_matrix.py          # rewrite the block
    python scripts/sync_compliance_matrix.py --check  # exit 1 if stale, change nothing
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GATES = ROOT / "bench" / "results" / "gates.json"
MATRIX = ROOT / "docs" / "compliance_matrix.md"
BEGIN = "<!-- GATES:BEGIN -- generated by scripts/sync_compliance_matrix.py, do not edit -->"
END = "<!-- GATES:END -->"

STATUS_WORD = {"MET": "**MET**", "NOT MET": "**NOT MET**", "NOT MEASURED": "**NOT MEASURED**"}


def render(gates: dict) -> str:
    rows = gates["rows"]
    out = [BEGIN, "",
           "| Gate | Tier | Target | Result | Status |",
           "|---|---|---|---|---|"]
    for r in rows:
        out.append(f"| {r['gate']} | {r['tier']} | {r['target']} | {r['result']} | "
                   f"{STATUS_WORD.get(r['status'], r['status'])} |")

    tally = {}
    for r in rows:
        tally[r["status"]] = tally.get(r["status"], 0) + 1
    met = tally.get("MET", 0)
    not_met = tally.get("NOT MET", 0)
    not_measured = tally.get("NOT MEASURED", 0)
    out += ["",
            f"**{met} met, {not_met} not met, {not_measured} not measured "
            f"({len(rows)} gates).**",
            "",
            END]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed file is stale; change nothing")
    args = ap.parse_args()

    if not GATES.is_file():
        print(f"{GATES.relative_to(ROOT)} is missing; run bench/gates.py first", file=sys.stderr)
        return 1

    text = MATRIX.read_text()
    if BEGIN not in text or END not in text:
        print(f"{MATRIX.relative_to(ROOT)} has no GATES markers; add them around the gate table",
              file=sys.stderr)
        return 1

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = head + render(json.loads(GATES.read_text())) + tail

    if updated == text:
        print("compliance matrix gate table is in sync with gates.json")
        return 0
    if args.check:
        print(f"{MATRIX.relative_to(ROOT)} is STALE: its gate table does not match "
              f"{GATES.relative_to(ROOT)}. Run scripts/sync_compliance_matrix.py", file=sys.stderr)
        return 1

    MATRIX.write_text(updated)
    print(f"updated the gate table in {MATRIX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
